import type { ActivityLog, ApiCategory, ApiProduct, AppItem } from "./types";

export const categories: ApiCategory[] = [
  "全部",
  "身份核验",
  "企业数据",
  "智能识别",
  "位置服务",
  "消息通信",
  "生活服务",
];

export const apiProducts: ApiProduct[] = [
  {
    id: "api_001",
    slug: "enterprise-verify",
    name: "企业工商信息核验",
    shortName: "企",
    category: "企业数据",
    description: "按企业名称或统一社会信用代码，返回工商主体、经营状态和风险摘要。",
    method: "POST",
    endpoint: "/v1/enterprise/verify",
    latency: 86,
    uptime: 99.99,
    calls: "2.8 亿",
    price: "¥0.03 / 次",
    tags: ["实时", "全国覆盖", "企业认证"],
    featured: true,
    verified: true,
    provider: "星枢数据",
    color: "#08785d",
  },
  {
    id: "api_002",
    slug: "idcard-two-factor",
    name: "身份证二要素核验",
    shortName: "证",
    category: "身份核验",
    description: "校验姓名与身份证号是否一致，适用于开户、签约和实名准入。",
    method: "POST",
    endpoint: "/v1/identity/idcard/check",
    latency: 112,
    uptime: 99.97,
    calls: "1.6 亿",
    price: "¥0.08 / 次",
    tags: ["加密传输", "合规审计"],
    featured: true,
    verified: true,
    provider: "国信认证",
    color: "#285c9f",
  },
  {
    id: "api_003",
    slug: "invoice-ocr",
    name: "增值税发票识别",
    shortName: "票",
    category: "智能识别",
    description: "识别全票面字段并完成金额勾稽校验，支持电子票与纸质票。",
    method: "POST",
    endpoint: "/v1/ocr/invoice",
    latency: 438,
    uptime: 99.95,
    calls: "8,450 万",
    price: "¥0.06 / 次",
    tags: ["OCR", "结构化输出"],
    verified: true,
    provider: "明眸智能",
    color: "#8a5426",
  },
  {
    id: "api_004",
    slug: "ip-location",
    name: "IP 归属地查询",
    shortName: "IP",
    category: "位置服务",
    description: "提供 IPv4/IPv6 地理位置、运营商、时区和风险网络识别。",
    method: "GET",
    endpoint: "/v1/network/ip",
    latency: 23,
    uptime: 99.999,
    calls: "12.4 亿",
    price: "免费 10 万次/月",
    tags: ["IPv6", "边缘节点"],
    featured: true,
    verified: true,
    provider: "星枢网络",
    color: "#475569",
  },
  {
    id: "api_005",
    slug: "sms-notification",
    name: "企业短信通知",
    shortName: "信",
    category: "消息通信",
    description: "验证码、通知与营销短信统一发送，支持回执和上行消息。",
    method: "POST",
    endpoint: "/v1/message/sms/send",
    latency: 168,
    uptime: 99.98,
    calls: "6.2 亿",
    price: "¥0.035 / 条起",
    tags: ["三网合一", "回执"],
    verified: true,
    provider: "云讯通",
    color: "#72672d",
  },
  {
    id: "api_006",
    slug: "weather-live",
    name: "全国实时天气",
    shortName: "天",
    category: "生活服务",
    description: "覆盖区县级实时天气、逐小时预报、空气质量与灾害预警。",
    method: "GET",
    endpoint: "/v1/weather/live",
    latency: 41,
    uptime: 99.99,
    calls: "9.7 亿",
    price: "免费 5 万次/月",
    tags: ["区县级", "灾害预警"],
    verified: true,
    provider: "风云数据",
    color: "#32758a",
  },
  {
    id: "api_007",
    slug: "bankcard-three-factor",
    name: "银行卡三要素核验",
    shortName: "卡",
    category: "身份核验",
    description: "校验姓名、身份证号与银行卡号的一致性，支持主流银行。",
    method: "POST",
    endpoint: "/v1/identity/bankcard/check",
    latency: 126,
    uptime: 99.96,
    calls: "7,600 万",
    price: "¥0.12 / 次",
    tags: ["金融级", "脱敏返回"],
    verified: true,
    provider: "国信认证",
    color: "#694b8f",
  },
  {
    id: "api_008",
    slug: "logistics-track",
    name: "物流轨迹订阅",
    shortName: "运",
    category: "生活服务",
    description: "识别快递公司并订阅物流节点，通过 Webhook 实时推送状态。",
    method: "POST",
    endpoint: "/v1/logistics/subscribe",
    latency: 74,
    uptime: 99.94,
    calls: "3.1 亿",
    price: "¥0.02 / 单",
    tags: ["Webhook", "自动识别"],
    verified: true,
    provider: "路由云",
    color: "#aa5d3a",
  },
];

export const activityLogs: ActivityLog[] = [
  { id: "req_91DSK", time: "14:32:18", api: "企业工商信息核验", app: "供应链生产环境", status: 200, latency: 82, region: "华东-上海" },
  { id: "req_91DSJ", time: "14:32:16", api: "IP 归属地查询", app: "官网服务", status: 200, latency: 21, region: "华南-广州" },
  { id: "req_91DSH", time: "14:32:11", api: "身份证二要素核验", app: "客户准入系统", status: 429, latency: 8, region: "华北-北京" },
  { id: "req_91DSF", time: "14:32:03", api: "全国实时天气", app: "运营大屏", status: 200, latency: 43, region: "西南-成都" },
  { id: "req_91DSE", time: "14:31:57", api: "增值税发票识别", app: "财务共享中心", status: 200, latency: 416, region: "华东-杭州" },
];

export const apps: AppItem[] = [
  { id: "app_1", name: "供应链生产环境", env: "生产", keyPrefix: "sk_live_9f2a", calls: "628.4 万", quota: 64, status: "运行中", lastUsed: "刚刚" },
  { id: "app_2", name: "客户准入系统", env: "生产", keyPrefix: "sk_live_3bc1", calls: "182.7 万", quota: 38, status: "运行中", lastUsed: "2 分钟前" },
  { id: "app_3", name: "联调沙箱", env: "测试", keyPrefix: "sk_test_72ad", calls: "3.2 万", quota: 12, status: "运行中", lastUsed: "昨天 18:42" },
];

export const usageSeries = [
  { date: "07-30", success: 83, failed: 5 },
  { date: "07-31", success: 96, failed: 3 },
  { date: "08-01", success: 88, failed: 6 },
  { date: "08-02", success: 118, failed: 4 },
  { date: "08-03", success: 108, failed: 3 },
  { date: "08-04", success: 132, failed: 6 },
  { date: "08-05", success: 147, failed: 4 },
];
