import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, CircleDollarSign, Clock3, KeyRound, MoreHorizontal, TrendingUp } from "lucide-react";
import { UsageChart } from "@/components/usage-chart";
import { activityLogs } from "@/lib/data";

const metrics = [
  { label: "今日调用量", value: "148.6 万", change: "+12.8%", icon: TrendingUp, tone: "text-[var(--brand)]" },
  { label: "成功率", value: "99.82%", change: "+0.06%", icon: CheckCircle2, tone: "text-[var(--brand)]" },
  { label: "P95 响应时间", value: "126 ms", change: "-18 ms", icon: Clock3, tone: "text-[#28609a]" },
  { label: "本月预估费用", value: "¥ 12,684", change: "预算 63%", icon: CircleDollarSign, tone: "text-[var(--warning)]" },
];

export default function ConsolePage() {
  return <div className="mx-auto max-w-[1440px] space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">WORKSPACE OVERVIEW</p><h2 className="mt-1 text-xl font-bold">工作空间概览</h2><p className="mt-1 text-[11px] text-[var(--muted)]">调用服务整体稳定，1 条配额告警需要处理。</p></div><div className="flex gap-2"><Link href="/console/apps" className="inline-flex h-9 items-center gap-2 rounded-[4px] border border-[var(--line-strong)] bg-white px-3 text-[10px] font-semibold hover:bg-[var(--surface-subtle)]"><KeyRound className="size-3.5" /> 管理密钥</Link><Link href="/" className="inline-flex h-9 items-center gap-2 rounded-[4px] bg-[var(--brand)] px-3 text-[10px] font-semibold text-white">添加 API <ArrowRight className="size-3" /></Link></div></div>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <section key={metric.label} className="panel p-4"><div className="flex items-center justify-between"><span className="text-[10px] text-[var(--muted)]">{metric.label}</span><metric.icon className={`size-4 ${metric.tone}`} /></div><strong className="mt-4 block text-2xl">{metric.value}</strong><span className={`mt-1 block text-[9px] ${metric.tone}`}>{metric.change}</span></section>)}</div>

    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.65fr)]"><section className="panel min-w-0 p-4 sm:p-5"><div className="flex items-start justify-between"><div><h3 className="text-[13px] font-bold">调用趋势</h3><p className="mt-1 text-[9px] text-[var(--muted)]">最近 7 天 · 单位：万次</p></div><select className="rounded-[4px] border border-[var(--line)] bg-white px-2 py-1.5 text-[10px]"><option>全部应用</option><option>供应链生产环境</option></select></div><div className="mt-4"><UsageChart /></div></section>
    <aside className="panel p-4 sm:p-5"><div className="flex items-center justify-between"><h3 className="text-[13px] font-bold">服务健康度</h3><MoreHorizontal className="size-4 text-[var(--muted)]" /></div><div className="mt-5 flex items-center gap-4"><div className="relative grid size-20 shrink-0 place-items-center rounded-full" style={{ background: "conic-gradient(#08785d 0 98.8%, #e5e9e7 98.8%)" }}><div className="grid size-16 place-items-center rounded-full bg-white"><span className="text-center"><strong className="block text-lg">98.8</strong><small className="text-[8px] text-[var(--muted)]">HEALTH</small></span></div></div><div className="space-y-2 text-[10px]"><p><span className="mr-2 inline-block size-1.5 rounded-full bg-[var(--brand)]" />7 个服务正常</p><p><span className="mr-2 inline-block size-1.5 rounded-full bg-[var(--warning)]" />1 个接近配额</p><p><span className="mr-2 inline-block size-1.5 rounded-full bg-[var(--line-strong)]" />0 个服务中断</p></div></div><div className="mt-5 rounded-[4px] bg-[var(--warning-soft)] p-3"><div className="flex gap-2"><AlertTriangle className="mt-0.5 size-3.5 shrink-0 text-[var(--warning)]" /><div><strong className="text-[10px] text-[#784707]">身份证核验配额达到 82%</strong><p className="mt-1 text-[9px] leading-4 text-[#8d642e]">按当前趋势预计 8 月 23 日耗尽。</p></div></div></div><button className="mt-4 w-full text-center text-[10px] font-semibold text-[var(--brand)]">查看全部服务状态</button></aside></div>

    <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] px-4 py-3.5 sm:px-5"><div><h3 className="text-[13px] font-bold">实时调用</h3><p className="mt-0.5 text-[9px] text-[var(--muted)]">最近请求，每 10 秒自动刷新</p></div><Link href="/console/logs" className="text-[10px] font-semibold text-[var(--brand)]">查看全部</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[10px]"><thead className="bg-[var(--surface-subtle)] text-[var(--muted)]"><tr><th className="px-5 py-2.5 font-medium">时间</th><th className="px-5 py-2.5 font-medium">接口</th><th className="px-5 py-2.5 font-medium">应用</th><th className="px-5 py-2.5 font-medium">状态</th><th className="px-5 py-2.5 font-medium">耗时</th><th className="px-5 py-2.5 font-medium">节点</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{activityLogs.map((log) => <tr key={log.id} className="hover:bg-[var(--surface-subtle)]"><td className="mono px-5 py-3 text-[var(--muted)]">{log.time}</td><td className="px-5 py-3 font-medium">{log.api}</td><td className="px-5 py-3 text-[var(--muted)]">{log.app}</td><td className="px-5 py-3"><span className={log.status === 200 ? "text-[var(--brand)]" : "text-[var(--warning)]"}>{log.status}</span></td><td className="mono px-5 py-3">{log.latency}ms</td><td className="px-5 py-3 text-[var(--muted)]">{log.region}</td></tr>)}</tbody></table></div></section>
  </div>;
}
