"use client";

import { Check, Copy, Eye, EyeOff, KeyRound, MoreHorizontal, Plus, X } from "lucide-react";
import { useState } from "react";
import { apps as initialApps } from "@/lib/data";

export function AppsManager() {
  const [showKey, setShowKey] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [name, setName] = useState("");
  const generatedKey = "sk_live_9f2a7c4e8d21b6f308a1";

  async function copyKey() { await navigator.clipboard.writeText(generatedKey); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }

  return <div className="mx-auto max-w-[1440px] space-y-5">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">APPLICATIONS</p><h2 className="mt-1 text-xl font-bold">应用与 API 密钥</h2><p className="mt-1 text-[11px] text-[var(--muted)]">按系统和环境隔离密钥、配额与调用日志。</p></div><button onClick={() => setDialogOpen(true)} className="inline-flex h-9 items-center justify-center gap-2 rounded-[4px] bg-[var(--brand)] px-4 text-[10px] font-semibold text-white"><Plus className="size-3.5" /> 创建应用</button></div>
    <div className="rounded-[4px] border border-[#c8e2d8] bg-[var(--brand-soft)] p-3 text-[10px] leading-5 text-[var(--brand-strong)]"><strong>密钥安全建议：</strong>生产密钥仅在创建时展示完整值。请使用服务端环境变量保存，并至少每 90 天轮换一次。</div>
    <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{initialApps.map((app) => <article key={app.id} className="panel p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-[5px] bg-[var(--surface-subtle)]"><KeyRound className="size-4 text-[var(--brand)]" /></span><div><h3 className="text-[12px] font-bold">{app.name}</h3><p className="mt-0.5 text-[9px] text-[var(--muted)]">{app.id} · {app.env}环境</p></div></div><button className="grid size-7 place-items-center text-[var(--muted)]" aria-label="更多操作"><MoreHorizontal className="size-4" /></button></div><div className="mt-5 flex items-center gap-2 border border-[var(--line)] bg-[var(--canvas)] p-2.5"><code className="mono flex-1 text-[10px]">{showKey ? generatedKey : `${app.keyPrefix}••••••••••••`}</code><button onClick={() => setShowKey((value) => !value)} aria-label={showKey ? "隐藏密钥" : "显示密钥"}>{showKey ? <EyeOff className="size-3.5 text-[var(--muted)]" /> : <Eye className="size-3.5 text-[var(--muted)]" />}</button></div><div className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><div><span className="text-[var(--muted)]">本月调用</span><strong className="mt-1 block text-[13px]">{app.calls}</strong></div><div><span className="text-[var(--muted)]">最近使用</span><strong className="mt-1 block text-[11px]">{app.lastUsed}</strong></div></div><div className="mt-4"><div className="mb-1.5 flex justify-between text-[9px]"><span className="text-[var(--muted)]">月度配额</span><span>{app.quota}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[var(--surface-subtle)]"><div className="h-full rounded-full bg-[var(--brand)]" style={{ width: `${app.quota}%` }} /></div></div><div className="mt-4 flex items-center justify-between border-t border-[var(--line)] pt-3"><span className="inline-flex items-center gap-1.5 text-[9px] text-[var(--brand)]"><span className="size-1.5 rounded-full bg-[var(--brand)]" />{app.status}</span><button className="text-[9px] font-semibold text-[var(--brand)]">管理应用</button></div></article>)}</div>
    {dialogOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4" role="presentation" onMouseDown={() => setDialogOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="new-app-title" className="w-full max-w-md rounded-[6px] bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-4"><h3 id="new-app-title" className="text-[13px] font-bold">创建企业应用</h3><button onClick={() => setDialogOpen(false)} aria-label="关闭"><X className="size-4 text-[var(--muted)]" /></button></div><div className="space-y-4 p-5"><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">应用名称</span><input value={name} onChange={(event) => setName(event.target.value)} autoFocus placeholder="例如：订单生产环境" className="h-10 w-full border border-[var(--line)] px-3 text-[11px] outline-none focus:border-[var(--brand)]" /></label><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">运行环境</span><select className="h-10 w-full border border-[var(--line)] bg-white px-3 text-[11px]"><option>生产环境</option><option>测试环境</option></select></label>{name && <div className="rounded-[4px] bg-[var(--warning-soft)] p-3"><p className="text-[9px] font-semibold text-[#784707]">预览密钥（创建后仅显示一次）</p><div className="mt-2 flex items-center gap-2"><code className="mono min-w-0 flex-1 truncate text-[9px] text-[#784707]">{generatedKey}</code><button onClick={copyKey}>{copied ? <Check className="size-3 text-[var(--brand)]" /> : <Copy className="size-3 text-[#784707]" />}</button></div></div>}</div><div className="flex justify-end gap-2 border-t border-[var(--line)] px-5 py-4"><button onClick={() => setDialogOpen(false)} className="h-9 rounded-[4px] border border-[var(--line)] px-4 text-[10px] font-semibold">取消</button><button disabled={!name} onClick={() => setDialogOpen(false)} className="h-9 rounded-[4px] bg-[var(--brand)] px-4 text-[10px] font-semibold text-white disabled:opacity-40">创建并生成密钥</button></div></div></div>}
  </div>;
}
