"use client";

import { CheckCircle2, Loader2, Save } from "lucide-react";
import { type FormEvent, useState } from "react";

export type TenantSettings = { name: string; type: "PERSONAL" | "ENTERPRISE"; creditCode: string | null; notificationEmail: string | null; timezone: string; quotaAlerts: boolean; canManage: boolean };

export function SettingsForm({ settings }: { settings: TenantSettings }) {
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/v1/tenant/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), creditCode: form.get("creditCode"), notificationEmail: form.get("notificationEmail"), timezone: form.get("timezone"), quotaAlerts: form.get("quotaAlerts") === "on" }) }); const result = await response.json(); if (!response.ok) { setError(result.message); return; } setMessage(result.message); } catch { setError("无法连接工作区设置服务"); } finally { setSaving(false); } }
  const input = "h-10 w-full rounded-[6px] border border-[var(--line)] bg-[var(--surface)] px-3 text-[11px] outline-none focus:border-[var(--brand)] disabled:opacity-60";
  return <form onSubmit={submit} className="mx-auto max-w-3xl space-y-5"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h2 className="mt-1 text-xl font-bold">工作区设置</h2><p className="mt-1 text-[11px] text-[var(--muted)]">维护当前{settings.type === "ENTERPRISE" ? "企业" : "个人"}空间的真实资料与通知偏好。</p></div><section className="panel"><div className="border-b border-[var(--line)] px-5 py-4"><h3 className="text-[13px] font-bold">基本信息</h3></div><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="mb-1.5 block text-[10px] font-semibold">工作区名称</span><input name="name" required minLength={2} defaultValue={settings.name} disabled={!settings.canManage} className={input} /></label>{settings.type === "ENTERPRISE" && <label className="block sm:col-span-2"><span className="mb-1.5 block text-[10px] font-semibold">统一社会信用代码</span><input name="creditCode" defaultValue={settings.creditCode ?? ""} disabled={!settings.canManage} className={input} /></label>}<label className="block"><span className="mb-1.5 block text-[10px] font-semibold">通知邮箱</span><input name="notificationEmail" type="email" defaultValue={settings.notificationEmail ?? ""} disabled={!settings.canManage} className={input} /></label><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">时区</span><select name="timezone" defaultValue={settings.timezone} disabled={!settings.canManage} className={input}><option value="Asia/Shanghai">Asia/Shanghai (UTC+8)</option><option value="UTC">UTC</option></select></label></div></section><section className="panel px-5"><label className="flex items-center justify-between gap-4 py-4"><span><strong className="block text-[11px]">配额阈值邮件提醒</strong><small className="mt-1 block text-[9px] text-[var(--muted)]">需要同时启用平台 SMTP 配置和工作区通知邮箱。</small></span><input name="quotaAlerts" type="checkbox" defaultChecked={settings.quotaAlerts} disabled={!settings.canManage} className="size-4 accent-[var(--brand)]" /></label></section>{error && <p role="alert" className="rounded-[6px] bg-[var(--danger-soft)] px-3 py-2 text-[10px] text-[var(--danger)]">{error}</p>}<div className="flex justify-end gap-3">{message && <span className="inline-flex items-center gap-1 text-[10px] text-[var(--success)]"><CheckCircle2 className="size-3.5" />{message}</span>}{settings.canManage && <button disabled={saving} className="inline-flex h-9 items-center gap-2 rounded-[6px] bg-[var(--brand)] px-4 text-[10px] font-semibold text-white disabled:opacity-50">{saving ? <Loader2 className="size-3.5 animate-spin" /> : <Save className="size-3.5" />}{saving ? "正在保存" : "保存更改"}</button>}</div></form>;
}
