"use client";

import { CheckCircle2, Loader2, MailCheck, Save } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Button } from "./ui/button";
import { FormField, FormLabel } from "./ui/form-field";
import { Input } from "./ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Switch } from "./ui/switch";

export type TenantSettings = { name: string; type: "PERSONAL" | "ENTERPRISE"; creditCode: string | null; notificationEmail: string | null; timezone: string; quotaAlerts: boolean; balanceAlerts: boolean; canManage: boolean };

export function SettingsForm({ settings }: { settings: TenantSettings }) {
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [notificationEmail, setNotificationEmail] = useState(settings.notificationEmail ?? "");
  const [verificationTarget, setVerificationTarget] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const normalizedEmail = notificationEmail.trim().toLowerCase(); try { const response = await fetch("/api/v1/tenant/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: String(form.get("name") ?? ""), creditCode: String(form.get("creditCode") ?? ""), notificationEmail: normalizedEmail, ...(verificationTarget === normalizedEmail ? { notificationCode: String(form.get("notificationCode") ?? "") || undefined } : {}), timezone: String(form.get("timezone") ?? ""), quotaAlerts: form.get("quotaAlerts") === "on", balanceAlerts: form.get("balanceAlerts") === "on" }) }); const result = await response.json(); if (response.status === 202) { setNotificationEmail(result.data.targetEmail); setVerificationTarget(result.data.targetEmail); setMessage(result.message); return; } if (!response.ok) { setError(result.message); return; } setNotificationEmail(result.data.notificationEmail ?? ""); setVerificationTarget(""); setMessage(result.message); } catch { setError("无法连接工作区设置服务"); } finally { setSaving(false); } }
  const verificationVisible = verificationTarget !== "" && verificationTarget === notificationEmail.trim().toLowerCase();
  return <form onSubmit={submit} className="mx-auto max-w-3xl space-y-5"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h2 className="mt-1 text-xl font-bold">工作区设置</h2><p className="mt-1 text-[11px] text-[var(--muted)]">维护当前{settings.type === "ENTERPRISE" ? "企业" : "个人"}空间的真实资料与通知偏好。</p></div><section className="panel"><div className="border-b border-[var(--line)] px-5 py-4"><h3 className="text-[13px] font-bold">基本信息</h3></div><div className="grid gap-4 p-5 sm:grid-cols-2"><FormField className="sm:col-span-2"><FormLabel>工作区名称</FormLabel><Input name="name" required minLength={2} defaultValue={settings.name} disabled={!settings.canManage} /></FormField>{settings.type === "ENTERPRISE" && <FormField className="sm:col-span-2"><FormLabel>统一社会信用代码</FormLabel><Input name="creditCode" defaultValue={settings.creditCode ?? ""} disabled={!settings.canManage} /></FormField>}<FormField><FormLabel>通知邮箱</FormLabel><Input name="notificationEmail" type="email" value={notificationEmail} onChange={(event) => { setNotificationEmail(event.target.value); setVerificationTarget(""); }} disabled={!settings.canManage} /></FormField><FormField><FormLabel>时区</FormLabel><Select name="timezone" defaultValue={settings.timezone} disabled={!settings.canManage}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Asia/Shanghai">Asia/Shanghai (UTC+8)</SelectItem><SelectItem value="UTC">UTC</SelectItem></SelectContent></Select></FormField>{verificationVisible && <FormField className="sm:col-span-2"><FormLabel>通知邮箱验证码</FormLabel><div className="flex gap-2"><Input name="notificationCode" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" placeholder="000000" className="mono text-center text-lg" /><span className="inline-flex shrink-0 items-center gap-1 rounded-[var(--radius-control)] bg-[var(--brand-soft)] px-3 text-[10px] text-[var(--brand-strong)]"><MailCheck className="size-3.5" />10 分钟有效</span></div></FormField>}</div></section><section className="panel divide-y divide-[var(--line)] px-5"><AlertToggle name="quotaAlerts" title="配额阈值邮件提醒" description="月调用量跨越管理员设置的阈值时发送。" defaultChecked={settings.quotaAlerts} disabled={!settings.canManage} /><AlertToggle name="balanceAlerts" title="余额不足邮件提醒" description="余额跨越管理员设置的低余额阈值时发送。" defaultChecked={settings.balanceAlerts} disabled={!settings.canManage} /></section>{error && <p role="alert" className="rounded-[var(--radius-control)] bg-[var(--danger-soft)] px-3 py-2 text-[10px] text-[var(--danger)]">{error}</p>}<div className="flex items-center justify-end gap-3">{message && <span className="inline-flex items-center gap-1 text-[10px] text-[var(--success)]"><CheckCircle2 className="size-3.5" />{message}</span>}{settings.canManage && <Button disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : <Save />}{saving ? "正在保存" : verificationVisible ? "验证并保存" : "保存更改"}</Button>}</div></form>;
}

function AlertToggle({ name, title, description, defaultChecked, disabled }: { name: string; title: string; description: string; defaultChecked: boolean; disabled: boolean }) {
  const [checked, setChecked] = useState(defaultChecked);
  return <label className="flex items-center justify-between gap-4 py-4"><span><strong className="block text-[11px]">{title}</strong><small className="mt-1 block text-[9px] text-[var(--muted)]">{description}</small></span><Switch name={name} checked={checked} onCheckedChange={setChecked} disabled={disabled} value="on" /></label>;
}
