"use client";

import * as React from "react";
import * as SelectPrimitive from "@radix-ui/react-select";
import { Check, ChevronDown, ChevronUp } from "lucide-react";
import { cn } from "@/lib/utils";

export const Select = SelectPrimitive.Root;
export const SelectGroup = SelectPrimitive.Group;
export const SelectValue = SelectPrimitive.Value;

export function SelectTrigger({ className, size = "default", children, ...props }: React.ComponentProps<typeof SelectPrimitive.Trigger> & { size?: "sm" | "default" }) { return <SelectPrimitive.Trigger data-slot="select-trigger" data-size={size} className={cn("flex w-full items-center justify-between gap-2 rounded-[var(--radius-control)] border border-[var(--line)] bg-[var(--surface-raised)] px-3 text-left text-[11px] text-[var(--ink)] shadow-[var(--shadow-inset)] outline-none transition hover:border-[var(--line-strong)] focus:border-[var(--brand)] focus:ring-3 focus:ring-[var(--focus-soft)] data-[placeholder]:text-[var(--muted-soft)] disabled:opacity-50 data-[size=default]:h-10 data-[size=sm]:h-8 data-[size=sm]:text-[10px] [&>span:first-child]:min-w-0 [&>span:first-child]:truncate", className)} {...props}>{children}<SelectPrimitive.Icon asChild><ChevronDown className="size-3.5 shrink-0 text-[var(--muted)]" /></SelectPrimitive.Icon></SelectPrimitive.Trigger>; }
export function SelectContent({ className, children, position = "popper", ...props }: React.ComponentProps<typeof SelectPrimitive.Content>) { return <SelectPrimitive.Portal><SelectPrimitive.Content position={position} data-slot="select-content" className={cn("z-[90] max-h-[min(320px,var(--radix-select-content-available-height))] min-w-[var(--radix-select-trigger-width)] overflow-hidden rounded-[var(--radius-panel)] border border-[var(--line)] bg-[var(--surface)] shadow-[var(--shadow-lg)] data-[state=open]:animate-[ui-pop-in_150ms_ease-out]", position === "popper" && "translate-y-1", className)} {...props}><SelectPrimitive.ScrollUpButton className="flex h-6 items-center justify-center"><ChevronUp className="size-3.5" /></SelectPrimitive.ScrollUpButton><SelectPrimitive.Viewport className="p-1.5">{children}</SelectPrimitive.Viewport><SelectPrimitive.ScrollDownButton className="flex h-6 items-center justify-center"><ChevronDown className="size-3.5" /></SelectPrimitive.ScrollDownButton></SelectPrimitive.Content></SelectPrimitive.Portal>; }
export function SelectLabel({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Label>) { return <SelectPrimitive.Label className={cn("px-2 py-1.5 text-[9px] font-semibold text-[var(--muted)]", className)} {...props} />; }
export function SelectItem({ className, children, ...props }: React.ComponentProps<typeof SelectPrimitive.Item>) { return <SelectPrimitive.Item data-slot="select-item" className={cn("relative flex h-9 cursor-default select-none items-center rounded-[6px] py-1.5 pl-8 pr-8 text-[10px] outline-none data-[disabled]:opacity-50 data-[highlighted]:bg-[var(--surface-subtle)]", className)} {...props}><span className="absolute left-2 grid size-4 place-items-center"><SelectPrimitive.ItemIndicator><Check className="size-3.5 text-[var(--brand)]" /></SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>; }
export function SelectSeparator({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Separator>) { return <SelectPrimitive.Separator className={cn("my-1 h-px bg-[var(--line)]", className)} {...props} />; }
